<img src="./assets/ga-logo.png" style="float: left; margin: 20px; height: 55px">

# Modeling Workflow (Walkthrough) - Solution

---

### About
Model data from scratch: gather data, clean it, explore it, and then evaluate several models.

### Learning Objectives
- Gather, clean, explore and model a dataset from scratch.
- Split data into testing and training sets using both train/test split and cross-validation and apply both techniques to score a model.
- Evaluate several models.


### Notebook Guide

- Importing libaries
- Load the Data
- Data Cleaning:
     - Initial check
     - Clean up PhD column
     - Drop `NaN`s
- Feature engineering: Binarize `Private` column
- EDA:
     - `apps`
     - What else do we want to explore?
     - Create Histograms of All Numerical Columns
     - Plot a Heatmap of the Correlation Matrix
     - Use seaborn's `.pairplot()` method to create scatterplots
- Model Prep:
     - Create our features matrix (`X`) and target vector (`y`)
     - Train/test split
     - Scaling
     - Instantiate our model
- Evaluation
- LINE Assumptions

# Importing libaries
---

We'll need the following libraries for today's lesson:

1. `pandas`
2. `numpy`
3. `seaborn`
4. `matplotlib.pyplot`
4. `train_test_split` and `cross_val_score` from `sklearn`'s `model_selection` module
5. `LinearRegression`, `LassoCV` and `RidgeCV` from `sklearn`'s `linear_model` module
6. `StandardScaler` from `sklearn`'s `preprocessing` module
7. `mean_squared_error` from `sklearn`'s `metrics` module

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, LassoCV, RidgeCV,Lasso,Ridge
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, PowerTransformer, OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import GridSearchCV, train_test_split

# Load the Data

---

Today's [data set](http://www-bcf.usc.edu/~gareth/ISL/data.html) (`College.csv`) is from the [ISLR website](https://cran.r-project.org/web/packages/ISLR/ISLR.pdf) on page 5. 

Rename `Unnamed: 0` to `University`.

In [3]:
df = pd.read_csv('./data/College.csv')
df.rename(columns={'Unnamed: 0': 'University'}, inplace=True)
df.head()

,University,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
0,Abilene Christian University,Yes,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60
1,Adelphi University,Yes,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,29,30,12.2,16,10527,56
2,Adrian College,Yes,1428,1097,336,22,50,1036,99,11250,3750,400,1165,53,66,12.9,30,8735,54
3,Agnes Scott College,Yes,417,349,137,60,89,510,63,12960,5450,450,875,92,97,7.7,37,19016,59
4,Alaska Pacific University,Yes,193,146,55,16,44,249,869,7560,4120,800,1500,76,72,11.9,2,10922,15

### Data Dictionary

data dictionary for the college dataset features:

| Column Name | Data Description |
| :--- | :--- |
| **Private** | A factor with levels No and Yes indicating private or public university |
| **Apps** | Number of applications received |
| **Accept** | Number of applications accepted |
| **Enroll** | Number of new students enrolled |
| **Top10perc** | Pct. new students from top 10% of H.S. class |
| **Top25perc** | Pct. new students from top 25% of H.S. class |
| **F.Undergrad** | Number of fulltime undergraduates |
| **P.Undergrad** | Number of parttime undergraduates |
| **Outstate** | Out-of-state tuition |
| **Room.Board** | Room and board costs |
| **Books** | Estimated book costs |
| **Personal** | Estimated personal spending |
| **PhD** | Pct. of faculty with Ph.D.’s |
| **Terminal** | Pct. of faculty with terminal degree |
| **S.F.Ratio** | Student/faculty ratio |
| **perc.alumni** | Pct. alumni who donate |
| **Expend** | Instructional expenditure per student |
| **Grad.Rate** | Graduation rate |

 Lowercase and snakecase all column names.

# Data cleaning: Initial check
---

Check the following in the cells below:
1. Do we have any null values?
2. Are any numerical columns being read in as `object`?

In [4]:
# Check for nulls

In [5]:
# Check column data types

In [6]:
# Hmm... PHD

## Data cleaning: Clean up `PhD` column
---

`PhD` is being read in as a string because some of the cells contain non-numerical values. In the cell below, replace any non-numerical values with `NaN`'s, and change the column datatype to float.

In [8]:



# or:
#df['phd'] = df['phd'].map(lambda phd: np.nan if phd == '?' else float(phd))
#df['phd'] = np.where(df['phd'] == '?', np.nan, df['phd']).astype(float)
#df.loc[~df.phd.str.isdigit(), 'phd'] = np.nan

## Data cleaning: Drop `NaN`s
---

Since there are a small percentage of null cells, let's go ahead and drop them.

# Feature engineering: Binarize `Private` column
---

In the cells below, convert the `Private` column into numerical values.

## We need to do a one-hot encoder for 'private' column in our pipeline later
- for that: let's do binary encode manually and save it in private_bi
- during pipeline, we will use private column and drop the private_bi that we did

In [7]:




# df['private_bi'] = df['private'].map({'Yes': 1, 'No': 0})
# df['private_bi'] = df['private'].apply({'Yes': 1, 'No': 0})
# df['private_bi'] = df['private'].map(lambda s: int(s == 'Yes'))
# df['private_bi'] = np.where(df['private'] == 'Yes', 1, 0)

# EDA:

## EDA: Target Column `apps`

In [8]:
# do boxplot for the target using sns.boxplot

In [9]:
# Check what is that oulier value appears in the boxplot

In [11]:
# Check the shape

In [135]:
# We can make a decision to drop the outlier, if we want! Test it!

# df = df[df['apps'] < 30000]
# df.shape

## EDA: What else do we want to explore?
---

In [136]:
# show main descriptive statistics of the dataframe
df.describe()

,apps,accept,enroll,top10perc,top25perc,f_undergrad,p_undergrad,outstate,room_board,books,personal,phd,terminal,s_f_ratio,perc_alumni,expend,grad_rate,private_bi
count,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000,746.000000
mean,2973.171582,2000.930295,775.690349,27.509383,55.801609,3691.109920,858.910188,10423.294906,4360.679625,549.217158,1342.134048,72.545576,79.646113,14.069571,22.852547,9608.447721,65.379357,0.727882
std,3857.782299,2435.387731,926.811100,17.479439,19.676601,4864.967516,1539.748424,3990.394244,1099.690538,167.207450,679.323729,16.193418,14.596707,3.897791,12.358829,5131.058695,17.036859,0.445349
min,81.000000,72.000000,35.000000,1.000000,9.000000,139.000000,1.000000,2340.000000,1780.000000,96.000000,300.000000,8.000000,24.000000,2.500000,0.000000,3186.000000,10.000000,0.000000
25%,762.000000,589.750000,239.000000,15.000000,41.000000,984.250000,95.750000,7275.000000,3597.250000,450.500000,870.000000,62.000000,71.000000,11.500000,13.000000,6761.000000,53.000000,0.000000
50%,1543.500000,1108.000000,433.000000,23.000000,54.000000,1707.000000,351.500000,9967.500000,4194.500000,500.000000,1200.000000,75.000000,82.000000,13.600000,21.000000,8355.000000,65.000000,1.000000
75%,3577.500000,2379.500000,883.500000,35.000000,69.000000,3921.000000,967.750000,12878.500000,5068.000000,600.000000,1697.500000,85.000000,92.000000,16.400000,31.000000,10804.500000,78.000000,1.000000
max,48094.000000,26330.000000,6392.000000,96.000000,100.000000,31643.000000,21836.000000,21700.000000,8124.000000,2340.000000,6800.000000,100.000000,100.000000,39.800000,64.000000,56233.000000,100.000000,1.000000

In [12]:
# phd & grad rate exceed 100%, correct to make it 100 or remove that rows.





# or fix to make 100
# df['phd'] = np.minimum(df['phd'], 100)
# df['grad_rate'] = np.minimum(df['grad_rate'], 100)

In [14]:
# do another boxplot for the target

In [15]:
# do a histogram of the target to see the distrubution of the data

## EDA: Create Histograms of All Numerical Columns
---

In [16]:
# do histogram for all the numeric columns

## EDA: Plot a Heatmap of the Correlation Matrix
---

Heatmaps are an effective way to visually examine the correlational structure of your predictors.

In [13]:
# Create a filtered correlation that shows values higher than a threshold
# threshold = 0.6
# filtered_corr = df.corr(numeric_only=True)
# filtered_corr[filtered_corr.abs() < threshold] = np.nan

# # plot the correlation heatmap
# plt.figure(figsize=(15,15))
# sns.heatmap(filtered_corr, 
#             annot=True,
#            vmin = -1,
#            vmax = 1,
#            cmap = 'coolwarm');

##### What if I just wanted to look at the correlation to `apps`?

In [17]:
# plt.figure(figsize=(10,8))
# sns.heatmap(df.corr(numeric_only=True)[['apps']].sort_values(by='apps', ascending=False), 
#             annot=True,
#            vmin=-1,
#            vmax=1,
#            cmap = 'coolwarm');

## EDA: Use seaborn's `.pairplot()` method to create scatterplots 
---

Let's create a pairplot to see how some of our stronger predictors correlate to our target (`apps`). Instead of creating a pairplot of the entire DataFrame, we can use the `y_vars` and `x_vars` params to get a smaller subset.

In [18]:
# sns.pairplot(df, x_vars=['accept', 'enroll', 'phd', 'f_undergrad', 'perc_alumni'], 
#              y_vars=['apps'],
#              height=4,            # 👈 Makes each plot taller
#              aspect=0.8,          # 👈 Adjusts the width proportion
#              kind='reg',          # 👈 Automatically injects a linear regression line
#              plot_kws={
#                 'scatter_kws': {
#                     'alpha': 0.3, # 👈 Makes points semi-transparent to reveal data density
#                     's': 15       # 👈 Shrinks dot size so thousands of rows don't blob together
#                 },
#                 'line_kws': {'color': 'red'} # Makes the linear assumption highly visible
#              })

Let's create a pairplot to see how all predictors correlate to our target (`apps`).

In [19]:
# sns.pairplot(
#     df, 
#     x_vars=df.select_dtypes(include=['number']).columns.tolist(), 
#     y_vars=['apps'],
#     height=4,            # 👈 Makes each plot taller
#     aspect=0.8,          # 👈 Adjusts the width proportion
#     kind='reg',          # 👈 Automatically injects a linear regression line
#     plot_kws={
#         'scatter_kws': {
#             'alpha': 0.3, # 👈 Makes points semi-transparent to reveal data density
#             's': 15       # 👈 Shrinks dot size so thousands of rows don't blob together
#         },
#         'line_kws': {'color': 'red'} # Makes the linear assumption highly visible
#     }
# )

# Model Prep

## Model Prep: Create our features matrix (`X`) and target vector (`y`)
---

What should our features be?

The `apps` column is our label: the number of applications received by that university.

X will be dataframe without those columns:
```python
['university', 'accept', 'enroll', 'apps','private']
```
In the cell below, create your `X` and `y` variables.

## Model Prep: Train/test split
---

We always want to have a holdout set to test our model. Use the `train_test_split` function to split our `X` and `y` variables into a training set and a holdout set.

## Model Prep: Scaling
---

In the cell below, fit a `StandardScaler` to `X_train` and use it to transform both `X_train` and `X_test`. This is especially important when we learn about `Ridge` and `Lasso` next week!

## Model Instantiate
---

## Model Evaluation: Scoring
---

Use `.score` to evaluate the model.

## Model Evaluation: LINE Assumptions
---

* 1. Linearity: The relationship between predictors (\(X\)) and the target (\(Y\)) must be a straight line.
* 2. Independence: Prediction errors (residuals) must not be correlated with each other (e.g., avoid time-series tracking).
  3. Normality: The errors (residuals) follow a Normal distribution with mean 0
  4. Homoscedasticity: Prediction errors must maintain a constant variance across all levels of the predictors.
  5. No Multicollinearity: Independent variables (\(X\)) must not perfectly correlate with or predict each other

In [21]:
# N - Normality of errors
# y_pred = lr.predict(X_train)
# resids = y_train - y_pred

# plt.figure(figsize = (8, 6))
# plt.hist(resids, bins = 25, color = 'teal', edgecolor = 'black');

# Fine

In [22]:
# E - Equal variance of errors
# Residual plot
# plt.figure(figsize = (10, 7))
# plt.scatter(y_pred, resids, color = 'teal', edgecolor = 'black')
# plt.axhline(0, color = 'black');

# Heteroscedasticity (!!)

* #### Variance of the dependent variable varies and is not constant across the entire dataset.
    - What do we do? One option is to transform our dependent variable.
    - A common transformation is to simply take the log of the dependent variable
        * Note: If target has value less than 0 then use yeo-johnson power transformer instead of log

In [23]:
# What did this just do?
# plt.hist(y, bins = 25, color = 'darkred', edgecolor = 'black')
# plt.title('Distribution of `apps`');

In [24]:
# plt.hist(y_log, bins = 25, color = 'darkred', edgecolor = 'black')
# plt.title('Distribution of log(`apps`)');

## **Note**
> Logarithmic transformation is a convenient means of transforming a highly skewed variable into a more normalized dataset.

* #### Split the data again using target transformed y_log.

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X, y_log, test_size=.20,random_state = 42)

In [25]:
# fit standard scaler on X_train and transform to both X_train and X_test
# ss = StandardScaler()

# X_train = ss.fit_transform(X_train)
# X_test = ss.transform(X_test)

In [27]:



# E - Equal variance of errors
# Residual plot
# plt.figure(figsize = (10, 7))
# plt.scatter(y_pred, resids, color = 'teal', edgecolor = 'black')
# plt.axhline(0, color = 'black');

In [28]:
# train r2 score after doing log target

In [29]:
# test r2 score after doing log target

### 😔

## Let's say that this model DID actually perform better... what do I need to remember to do to make predictions?

## Model Prediction:
---

In [30]:
# You must use the exponential to "undo" our log transformation!

<div style="background-color: #f0f7ff; border-left: 5px solid #0066cc; padding: 15px; border-radius: 4px; margin: 20px 0;">
    <h3 style="color: #0066cc; margin: 0 0 5px 0; font-family: sans-serif; font-size: 18px; font-weight: bold;">
        🏁 End of Part One
    </h3>
    <p style="color: #334e68; margin: 0; font-family: sans-serif; font-size: 14px;">
        Data cleaning, exploratory visualizations, feature transformation,  and basic modeling Complete.
    </p>
</div>

# Enhance Modeling:

## 1. EDA: Check Skewness
---

Use the function that you created earlier in previous lab to check skewness

In [31]:
# import myutil script file to use the skew functions we created

In [36]:
# create a skewness table

In [35]:
# list all columns that doesn't have skewness

In [34]:
# list all columns that have skewness

In [33]:
# check skewness before and after

* Important: remove the target column from the skew_cols

In [37]:
# Important: remove the target column from the skew_cols

## 2. Model Prep: Using Pipeline all the way 
---

## Specify Features and Target 
---

In [178]:
# specify the X and the y (if y needs log or power then transform it here)
X = df.drop(columns=['university', 'accept', 'enroll', 'apps','private_bi'])
y_log = np.log(df['apps'])

# or if you want to use powertranfromer to transform y
# pt=PowerTransformer(method='yeo-johnson')
# y_log = pt.fit_transform(df[['apps']])

In [38]:
# List of columns that contains skewness



# notice that we need to remove the columns that was excluded from X features

## Split Train and Test
---

## Pipeline Prepare
---

In [42]:
# ==========================================
# 1. DEFINING SEPARATE PREPROCESSING SUB-PIPELINES
# ==========================================
# Sub-Pipeline A: For standard numeric data



# Sub-Pipeline B: For heavily skewed numeric data (uses a box-cox/yeo-johnson power transform)



# Sub-Pipeline C: For regular distinct categories Use OneHotEncoder




# ==========================================
# 2. Meging All the Columns WITH COLUMNTRANSFORMER
# ==========================================

In [43]:
# ==========================================
# 3. Building The Full Pipeline
#    3.1 Linear Regression
# ==========================================
# Build the main pipeline containing the preprocessor block and model

In [44]:
# ==========================================
# 3. Building The Full Pipeline
#    3.2 RidgeCV Regression
# ==========================================
# Build the main pipeline containing the preprocessor block and model

## Using GridsearchCV to do all the three models

In [46]:
# 4. Define the Parameter Grid
# Notice how we can swap out the entire 'regressor' step and its alpha weights!

In [47]:
# 6. View Results

# print(f"Best Parameters: {grid_search.best_params_}")
# print(f"Best CV R2 Score: {grid_search.best_score_:.4f}") # average score across CV validation folds
# print(f"Train R2 Score: {grid_search.best_estimator_.score(X_train,y_train):.4f}")
# print(f"Test R2 Score: {grid_search.best_estimator_.score(X_test,y_test):.4f}")

In [49]:
# what is grid search best_estimator_

# Save your model using joblib

In [50]:
# import joblib

# 1. Save the entire GridSearch object (or just the best pipeline)
# It is best practice to save the '.best_estimator_' to keep the file clean

In [51]:
# ----------------------------------------------------
# 2. Later (in your production or testing script):
# ----------------------------------------------------